### ISSUE TITLE
Upgrade fails with stacktrace.

### ISSUE THREAD

**Issue by erenfro** [armandg/sol3rd#3]
Running: `sol3rd -u`
Resulting output:

```
 [✔] Getting available versions                    
 [✔] Getting installed versions                        

Upgrading google-chrome-stable
Installed: 67.0.3396.87
Available: 67.0.3396.99
OK? (yes or no): yes
Traceback (most recent call last):
  File "/usr/bin/sol3rd", line 11, in <module>
    load_entry_point('sol3rd==0.1', 'console_scripts', 'sol3rd')()
  File "/usr/lib/python2.7/site-packages/sol3rd/sol3rd.py", line 202, in main
    apps_upgradeable = get_upgradeable()
  File "/usr/lib/python2.7/site-packages/sol3rd/sol3rd.py", line 138, in get_upgradeable
    do_upgrade = input('\nOK? (yes or no): ')
  File "<string>", line 1, in <module>
NameError: name 'yes' is not defined
```

**Comment by geirawsm** [comment]
Somewhat similar to error reported in #1.
